### ISSUE TITLE
📝 Register a new app

### ISSUE THREAD

**Issue by ymao2** [ministryofjustice/analytical-platform#1700] opened 2023-09-28 11:24 UTC
## Background

After finishing app-migration, we need to start to think about how to handle the request of registering a new app. 

The key points we need to consider 
- how to capture such request? : e.g. github issue or through cpanel 
- steps for creating required infrastructure (namespace, ecr ..) on CP, auth0 and getting the app ready in cpanel which allow users to manage the app through cpanel 
  - cluster related 
    - namespace
    - resources: etc.
    -  rbac
   - AWS app role + trust-relationships between AWS app role and CP role
   - Auth0 clients if auth is required 
   - github workflows
   - Register the app in Cpanel 
 - how about static page app?

## Current status for getting a app deployed 
**if something is missed, feel free to add them**
 - a few scripts + github workflow(?) for getting the infrastructure created on CP
 - cpanel has the feature of registering an app which will get aws-role, auth-clients and github secrets & vars created
There is no auto-step to link the above 2 steps.  There is question about what is the best way to add the trust-relationship
- **static page** (?)

## Done when 
- A user-story and related flows has been well-defined
- A list of break-down tasks

### List of issues in this epic

- [x] #1886
- [x] #1929
- [x] #2632
- [x] #2633
- [x] #2634
- [x] #2635
- [x] #2636
- [x] #2981
- [x] #3300

**Comment by julialawrence** [comment] 2024-02-26 08:12
Closing as duplicate of #1828

**Closed as completed by julialawrence** 2024-02-26 08:12 UTC
Labels: epic, data-platform-apps-and-tools
