### ISSUE TITLE
 ✨ mlflow UI on Analytical Platform

### ISSUE THREAD

**Issue by mshodge** [ministryofjustice/analytical-platform#3368] opened 2024-02-16 13:20 UTC
### Describe the feature request.

Hi there -

Data Scientists at MoJ routinely do Machine Learning work on the AP, but there is no centralised, structured way of them logging and recording their experiments and ML model performance. [mlflow](https://mlflow.org/) is a widely used tool by Data Scientists to record and assess performance of their ML models.

This request would be to help setup the backend storing of the model artefacts as well as helping setup the UI for AP users to look at their own, and others, ML performance and metrics.  

### Describe the context.

I am starting my role as MLOps coordinator from next week. Therefore I am highlighting MLOps needs as early as possible in the hopes that they can be made possible during my six month stint.

### Value / Purpose

Without a dedicated tool like mlflow, the impact of Data Science at MoJ will be greatly reduced. It will save time for the Data Scientists by providing a centralised store of their own model performance and metrics, but also provide them with the opportunity to see what others are doing. Without this approach, ML model metrics will forever be kept on scrap bits of paper and likely, lost

### User Types

Data Scientists doing ML

**Comment by mshodge** [comment] 2024-02-16 13:45
Note: Might be redundant if [SageMaker](https://aws.amazon.com/sagemaker/) is the chosen approach.

**Comment by Ed-Bajo** [comment] 2024-04-09 10:59
Meet to ascertain actual require and current state.

**Comment by michaeljcollinsuk** [comment] 2024-04-09 11:59
Related support issue https://github.com/ministryofjustice/data-platform-support/issues/527

**Comment by mshodge** [comment] 2024-04-11 10:43
Thanks @michaeljcollinsuk and @Ed-Bajo - bringing in @PriyaBasker23 to this as well. We've done a lot of work on this over the past few weeks on the sandbox and before we meet we will have a better ask for you and the team :)

**Comment by jacobwoffenden** [comment] 2024-07-10 15:39
Closing as duplicate of #4275

**Closed as not planned by jacobwoffenden** 2024-07-10 15:39 UTC
Labels: enhancement, feature-request
