### ISSUE TITLE
🗺️  Create Diagram of the AWS QuickSight Implementation

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#3229] opened 2024-02-07 09:02 UTC
The purpose of this ticket is to ensure that an architectural diagram of the QuickSight implementation is created and recorded in the appropriate location - ADR if necessary.

**Comment by Ed-Bajo** [comment] 2024-02-26 10:39
Duplicate of #3314

**Closed as not planned by Ed-Bajo** 2024-02-26 10:39 UTC
Labels: data-platform-apps-and-tools
